name: Build Project
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: xRealNeon/VuePagesAction@1.0.0
      with:
        username: Kerigard
        reponame: kerigard.github.io
        token: ${{ secrets.GITHUB_TOKEN }}
        gitname: GitHub Actions
        gitemail: 41898282+github-actions[bot]@users.noreply.github.com
