name: Build Project

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and push
        uses: xRealNeon/VuePagesAction@1.0.1
        with:
          username: Kerigard
          reponame: kerigard.github.io
          token: ${{ secrets.GITHUB_TOKEN }}
          gitname: GitHub Actions
          gitemail: 41898282+github-actions[bot]@users.noreply.github.com
          useyarn: true
